pipeline {
    agent any
    stages {
        stage("Maven Build"){
            steps {
                dir("horizonx-users") {
                    sh "mvn -B -Dskiptest clean package"
                }
            }
        }
        stage("Tests"){
            steps {
                dir("horizonx-users") {
                    sh "mvn test"
                }
            }
            post {
                always {
                    junit 'horizonx-users/target/surefire-reports/*.xml'
                }
            }
        }
        stage("Deliver"){
            steps {
                sh './horizonx-users/jenkins/scripts/deliver.sh'
            }
        }
    }
}