pipeline {
    agent any
    environment {
        def myString = "Shiva baba"
        def myNumber = 18
        def myBoolean = true
    }
    parameters {
        booleanParam(defaultValue: false, description: "Enable Service?", name: "boolean")
        choice(choices: ["IT", "UAT", "PRE-PROD", "PROD"], description: "Which environment to deploy", name: "env")
        string(defaultValue: "TEST", description: "Which Cloud venor is used ", name: "cloud")
    }
    stages {
        stage("Maven Build"){
            steps {
                dir("horizonx-users") {
                    sh "mvn -B -Dskiptest clean package"
                }
            }
        }
        stage("Tests"){
            steps {
                dir("horizonx-users") {
                    sh "mvn test"
                }
            }
            post {
                always {
                    junit 'horizonx-users/target/surefire-reports/*.xml'
                }
            }
        }
        stage("Boolean select"){
            steps {
                echo "booleanParam is set to : ${params.boolean}"
            }
        }
        stage("Dropdown select"){
            steps {
                echo "dropdown is set to : ${params.env}"
            }
        }
        stage("String input select"){
            steps {
                 echo "dropdown is set to : ${params.env}"
            }
        }
        stage("String variable"){
            steps {
                 echo "dropdown is set to : ${myString}"
                 sleep(10)
            }
        }
        stage("Number variable"){
            steps {
                 echo "dropdown is set to : ${myNumber}"
            }
        }
        stage("Boolean variable"){
            steps {
                 echo "dropdown is set to : ${myBoolean}"
            }
        }
        stage("Jenkins in-build variable 1"){
            steps {
                 echo "Current build number is : ${BUILD_NUMBER}"
            }
        }
        stage("Jenkins in-build variable 2"){
            steps {
                 echo "Current build Id is : ${BUILD_ID}" + "${JOB_NAME}"
            }
        }
    }
}