pipeline {
    agent any
    environment {
        def myString = "Shiva baba"
        def myNumber = 18
        def myBoolean = true
    }
    parameters {
        booleanParam(defaultValue: false, description: "Enable Service?", name: "boolean")
        choice(choices: ["IT", "UAT", "PRE-PROD", "PROD"], description: "Which environment to deploy", name: "env")
        string(defaultValue: "TEST", description: "Which Cloud venor is used ", name: "cloud")
    }
    stages {
        stage("Maven Build"){
            steps {
                dir("horizonx-users") {
                    sh "mvn -B -Dskiptest clean package"
                }
            }
        }
        stage("Tests"){
            steps {
                dir("horizonx-users") {
                    sh "mvn test"
                }
            }
            post {
                always {
                    junit 'horizonx-users/target/surefire-reports/*.xml'
                }
            }
        }
        stage("Boolean select"){
            steps {
                echo "booleanParam is set to : ${params.boolean}"
            }
        }
        stage("Want to launch?"){
            steps{
                scripts{
                    if(params.boolean == false) {
                        echo "Not going to launch"
                        currentBuild.result="SUCCESS"
                    } else {
                        echo "Successfully launched"
                    }
                }
            }
        }

    }
}